apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: iti-pro
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/MinaC4/iti-final-project.git
    targetRevision: HEAD
    path: helm/iti-pro
    helm:
      releaseName: iti-pro
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
  revisionHistoryLimit: 10
